name = "social-manager"
main = "src/worker/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "social.bits.co.id"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "social-manager-db"
database_id = "local-dev-id"
migrations_dir = "migrations"
